const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const path = require('path');
const dotenv = require('dotenv');
dotenv.config({ path: path.join(__dirname, '../.env') });

const User    = require('../models/User');
const Sample  = require('../models/Sample');
const connectDB = require('./db');

const daysAgo = (n) => new Date(Date.now() - n * 86400000);

const seed = async () => {
  await connectDB();
  await User.deleteMany();
  await Sample.deleteMany();

  const hashedPassword = await bcrypt.hash('password123', 10);
  const [researcher, technician] = await User.insertMany([
    { name: 'Dr. Priya Sharma', email: 'researcher@demo.com', password: hashedPassword, role: 'researcher', institution: 'AIIMS Delhi' },
    { name: 'Ravi Kumar',       email: 'technician@demo.com', password: hashedPassword, role: 'technician', institution: 'Safdarjung Hospital' },
  ]);
  const rid = researcher._id;
  const tid = technician._id;

  const samples = [

    // ── E. coli (20 samples) ─────────────────────────────────────────
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'ICU' }, antibiotics: [{ name: 'Ampicillin', mic: 64, result: 'R' }, { name: 'Ciprofloxacin', mic: 8, result: 'R' }, { name: 'Ceftriaxone', mic: 16, result: 'R' }, { name: 'Meropenem', mic: 0.25, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }], patientAge: 54, patientGender: 'Male', collectedAt: daysAgo(2), submittedBy: tid, notes: 'ESBL-producing strain suspected.' },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'General Ward' }, antibiotics: [{ name: 'Ampicillin', mic: 128, result: 'R' }, { name: 'Ciprofloxacin', mic: 1, result: 'S' }, { name: 'Ceftriaxone', mic: 2, result: 'S' }, { name: 'Trimethoprim-SMX', mic: 8, result: 'R' }, { name: 'Nitrofurantoin', mic: 16, result: 'S' }], patientAge: 32, patientGender: 'Female', collectedAt: daysAgo(5), submittedBy: tid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Urology' }, antibiotics: [{ name: 'Ampicillin', mic: 32, result: 'R' }, { name: 'Ciprofloxacin', mic: 4, result: 'I' }, { name: 'Ceftriaxone', mic: 4, result: 'I' }, { name: 'Meropenem', mic: 0.5, result: 'S' }, { name: 'Fosfomycin', mic: 8, result: 'S' }], patientAge: 67, patientGender: 'Male', collectedAt: daysAgo(10), submittedBy: tid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Yamuna River Bank', city: 'Delhi' }, antibiotics: [{ name: 'Ampicillin', mic: 256, result: 'R' }, { name: 'Ciprofloxacin', mic: 16, result: 'R' }, { name: 'Trimethoprim-SMX', mic: 32, result: 'R' }, { name: 'Tetracycline', mic: 32, result: 'R' }, { name: 'Chloramphenicol', mic: 16, result: 'R' }], collectedAt: daysAgo(8), submittedBy: rid, notes: 'High MDR load near hospital effluent.' },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Hospital Wastewater Outlet', city: 'Delhi' }, antibiotics: [{ name: 'Ampicillin', mic: 128, result: 'R' }, { name: 'Ciprofloxacin', mic: 8, result: 'R' }, { name: 'Meropenem', mic: 2, result: 'I' }, { name: 'Amikacin', mic: 8, result: 'S' }], collectedAt: daysAgo(14), submittedBy: rid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Nephrology' }, antibiotics: [{ name: 'Ampicillin', mic: 64, result: 'R' }, { name: 'Ciprofloxacin', mic: 2, result: 'S' }, { name: 'Ceftriaxone', mic: 1, result: 'S' }, { name: 'Meropenem', mic: 0.25, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }], patientAge: 45, patientGender: 'Female', collectedAt: daysAgo(18), submittedBy: tid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Surgery Ward' }, antibiotics: [{ name: 'Ampicillin', mic: 32, result: 'R' }, { name: 'Ciprofloxacin', mic: 16, result: 'R' }, { name: 'Ceftriaxone', mic: 32, result: 'R' }, { name: 'Meropenem', mic: 4, result: 'I' }, { name: 'Colistin', mic: 1, result: 'S' }], patientAge: 71, patientGender: 'Male', collectedAt: daysAgo(22), submittedBy: tid, notes: 'Post-surgical wound infection.' },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Paediatrics' }, antibiotics: [{ name: 'Ampicillin', mic: 16, result: 'R' }, { name: 'Ciprofloxacin', mic: 0.5, result: 'S' }, { name: 'Ceftriaxone', mic: 1, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }], patientAge: 4, patientGender: 'Male', collectedAt: daysAgo(30), submittedBy: tid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Obstetrics' }, antibiotics: [{ name: 'Ampicillin', mic: 64, result: 'R' }, { name: 'Ceftriaxone', mic: 2, result: 'S' }, { name: 'Nitrofurantoin', mic: 32, result: 'R' }, { name: 'Fosfomycin', mic: 4, result: 'S' }], patientAge: 28, patientGender: 'Female', collectedAt: daysAgo(35), submittedBy: tid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Groundwater Well', city: 'Dehradun' }, antibiotics: [{ name: 'Ampicillin', mic: 128, result: 'R' }, { name: 'Tetracycline', mic: 16, result: 'R' }, { name: 'Chloramphenicol', mic: 8, result: 'I' }, { name: 'Ciprofloxacin', mic: 4, result: 'R' }], collectedAt: daysAgo(40), submittedBy: rid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Oncology' }, antibiotics: [{ name: 'Ampicillin', mic: 64, result: 'R' }, { name: 'Ciprofloxacin', mic: 8, result: 'R' }, { name: 'Ceftriaxone', mic: 16, result: 'R' }, { name: 'Meropenem', mic: 8, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }], patientAge: 58, patientGender: 'Female', collectedAt: daysAgo(45), submittedBy: tid, notes: 'Pan-drug resistant strain. Last resort antibiotics only.' },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'ICU' }, antibiotics: [{ name: 'Ampicillin', mic: 32, result: 'R' }, { name: 'Ciprofloxacin', mic: 1, result: 'S' }, { name: 'Meropenem', mic: 0.5, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }], patientAge: 63, patientGender: 'Male', collectedAt: daysAgo(50), submittedBy: tid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Poultry Farm Runoff', city: 'Haridwar' }, antibiotics: [{ name: 'Ampicillin', mic: 256, result: 'R' }, { name: 'Tetracycline', mic: 64, result: 'R' }, { name: 'Ciprofloxacin', mic: 16, result: 'R' }, { name: 'Colistin', mic: 4, result: 'R' }], collectedAt: daysAgo(55), submittedBy: rid, notes: 'One Health surveillance. Colistin resistance detected.' },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Medicine Ward' }, antibiotics: [{ name: 'Ampicillin', mic: 16, result: 'R' }, { name: 'Ciprofloxacin', mic: 0.25, result: 'S' }, { name: 'Ceftriaxone', mic: 0.5, result: 'S' }, { name: 'Nitrofurantoin', mic: 16, result: 'S' }], patientAge: 39, patientGender: 'Female', collectedAt: daysAgo(60), submittedBy: tid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Neonatology' }, antibiotics: [{ name: 'Ampicillin', mic: 128, result: 'R' }, { name: 'Gentamicin', mic: 8, result: 'R' }, { name: 'Ceftriaxone', mic: 32, result: 'R' }, { name: 'Meropenem', mic: 1, result: 'S' }], patientAge: 0, patientGender: 'Female', collectedAt: daysAgo(65), submittedBy: tid, notes: 'Neonatal sepsis.' },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'River Ganga Tributary', city: 'Rishikesh' }, antibiotics: [{ name: 'Ampicillin', mic: 64, result: 'R' }, { name: 'Ciprofloxacin', mic: 4, result: 'R' }, { name: 'Trimethoprim-SMX', mic: 16, result: 'R' }, { name: 'Amikacin', mic: 8, result: 'S' }], collectedAt: daysAgo(70), submittedBy: rid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Emergency' }, antibiotics: [{ name: 'Ampicillin', mic: 32, result: 'R' }, { name: 'Ciprofloxacin', mic: 2, result: 'S' }, { name: 'Ceftriaxone', mic: 4, result: 'I' }, { name: 'Meropenem', mic: 0.5, result: 'S' }], patientAge: 52, patientGender: 'Male', collectedAt: daysAgo(75), submittedBy: tid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Geriatrics' }, antibiotics: [{ name: 'Ampicillin', mic: 64, result: 'R' }, { name: 'Ciprofloxacin', mic: 8, result: 'R' }, { name: 'Ceftriaxone', mic: 8, result: 'R' }, { name: 'Meropenem', mic: 2, result: 'I' }, { name: 'Amikacin', mic: 16, result: 'I' }], patientAge: 82, patientGender: 'Female', collectedAt: daysAgo(80), submittedBy: tid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Hospital Kitchen Water', city: 'Delhi' }, antibiotics: [{ name: 'Ampicillin', mic: 32, result: 'R' }, { name: 'Ciprofloxacin', mic: 2, result: 'S' }, { name: 'Chloramphenicol', mic: 8, result: 'I' }], collectedAt: daysAgo(85), submittedBy: rid },
    { pathogen: 'E. coli', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Orthopaedics' }, antibiotics: [{ name: 'Ampicillin', mic: 16, result: 'R' }, { name: 'Ciprofloxacin', mic: 4, result: 'I' }, { name: 'Ceftriaxone', mic: 2, result: 'S' }, { name: 'Meropenem', mic: 0.25, result: 'S' }], patientAge: 48, patientGender: 'Male', collectedAt: daysAgo(90), submittedBy: tid },

    // ── S. aureus (20 samples) ───────────────────────────────────────
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Surgery Ward' }, antibiotics: [{ name: 'Oxacillin', mic: 8, result: 'R' }, { name: 'Vancomycin', mic: 1, result: 'S' }, { name: 'Clindamycin', mic: 0.25, result: 'S' }, { name: 'Erythromycin', mic: 4, result: 'R' }, { name: 'Linezolid', mic: 2, result: 'S' }], patientAge: 45, patientGender: 'Male', collectedAt: daysAgo(3), submittedBy: tid, notes: 'MRSA confirmed. Contact precautions initiated.' },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Burns Unit' }, antibiotics: [{ name: 'Oxacillin', mic: 16, result: 'R' }, { name: 'Vancomycin', mic: 2, result: 'S' }, { name: 'Clindamycin', mic: 8, result: 'R' }, { name: 'Tetracycline', mic: 4, result: 'I' }, { name: 'Rifampicin', mic: 0.5, result: 'S' }], patientAge: 28, patientGender: 'Male', collectedAt: daysAgo(6), submittedBy: tid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Dermatology' }, antibiotics: [{ name: 'Oxacillin', mic: 1, result: 'S' }, { name: 'Erythromycin', mic: 1, result: 'R' }, { name: 'Clindamycin', mic: 0.5, result: 'S' }, { name: 'Tetracycline', mic: 2, result: 'S' }], patientAge: 19, patientGender: 'Female', collectedAt: daysAgo(12), submittedBy: tid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'ICU' }, antibiotics: [{ name: 'Oxacillin', mic: 32, result: 'R' }, { name: 'Vancomycin', mic: 1, result: 'S' }, { name: 'Linezolid', mic: 2, result: 'S' }, { name: 'Daptomycin', mic: 0.5, result: 'S' }, { name: 'Tigecycline', mic: 0.25, result: 'S' }], patientAge: 72, patientGender: 'Female', collectedAt: daysAgo(1), submittedBy: tid, notes: 'MRSA bacteremia. Blood culture positive x2.' },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'environmental', location: { site: 'OT Air Sample', city: 'Delhi' }, antibiotics: [{ name: 'Oxacillin', mic: 4, result: 'R' }, { name: 'Erythromycin', mic: 8, result: 'R' }, { name: 'Tetracycline', mic: 16, result: 'R' }], collectedAt: daysAgo(20), submittedBy: rid, notes: 'OT environmental surveillance.' },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Orthopaedics' }, antibiotics: [{ name: 'Oxacillin', mic: 2, result: 'S' }, { name: 'Erythromycin', mic: 4, result: 'R' }, { name: 'Clindamycin', mic: 1, result: 'S' }, { name: 'Ciprofloxacin', mic: 1, result: 'S' }], patientAge: 34, patientGender: 'Male', collectedAt: daysAgo(25), submittedBy: tid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Cardiology' }, antibiotics: [{ name: 'Oxacillin', mic: 16, result: 'R' }, { name: 'Vancomycin', mic: 2, result: 'S' }, { name: 'Rifampicin', mic: 0.5, result: 'S' }, { name: 'Linezolid', mic: 2, result: 'S' }, { name: 'Daptomycin', mic: 1, result: 'S' }], patientAge: 65, patientGender: 'Male', collectedAt: daysAgo(28), submittedBy: tid, notes: 'Infective endocarditis.' },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Paediatrics' }, antibiotics: [{ name: 'Oxacillin', mic: 0.5, result: 'S' }, { name: 'Erythromycin', mic: 0.5, result: 'S' }, { name: 'Clindamycin', mic: 0.25, result: 'S' }, { name: 'Trimethoprim-SMX', mic: 1, result: 'S' }], patientAge: 7, patientGender: 'Female', collectedAt: daysAgo(33), submittedBy: tid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'environmental', location: { site: 'ICU Surface Swab', city: 'Delhi' }, antibiotics: [{ name: 'Oxacillin', mic: 8, result: 'R' }, { name: 'Erythromycin', mic: 4, result: 'R' }, { name: 'Vancomycin', mic: 1, result: 'S' }], collectedAt: daysAgo(38), submittedBy: rid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Neurosurgery' }, antibiotics: [{ name: 'Oxacillin', mic: 32, result: 'R' }, { name: 'Vancomycin', mic: 1, result: 'S' }, { name: 'Clindamycin', mic: 4, result: 'R' }, { name: 'Rifampicin', mic: 1, result: 'I' }], patientAge: 44, patientGender: 'Male', collectedAt: daysAgo(42), submittedBy: tid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'General Surgery' }, antibiotics: [{ name: 'Oxacillin', mic: 1, result: 'S' }, { name: 'Erythromycin', mic: 8, result: 'R' }, { name: 'Tetracycline', mic: 4, result: 'I' }, { name: 'Ciprofloxacin', mic: 2, result: 'S' }], patientAge: 29, patientGender: 'Male', collectedAt: daysAgo(47), submittedBy: tid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Haematology' }, antibiotics: [{ name: 'Oxacillin', mic: 16, result: 'R' }, { name: 'Vancomycin', mic: 2, result: 'S' }, { name: 'Linezolid', mic: 2, result: 'S' }, { name: 'Tigecycline', mic: 0.5, result: 'S' }], patientAge: 53, patientGender: 'Female', collectedAt: daysAgo(52), submittedBy: tid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'environmental', location: { site: 'Nursing Station Surface', city: 'Delhi' }, antibiotics: [{ name: 'Oxacillin', mic: 4, result: 'R' }, { name: 'Erythromycin', mic: 8, result: 'R' }, { name: 'Tetracycline', mic: 8, result: 'R' }, { name: 'Vancomycin', mic: 1, result: 'S' }], collectedAt: daysAgo(57), submittedBy: rid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Orthopaedics' }, antibiotics: [{ name: 'Oxacillin', mic: 0.5, result: 'S' }, { name: 'Erythromycin', mic: 1, result: 'S' }, { name: 'Clindamycin', mic: 0.25, result: 'S' }, { name: 'Ciprofloxacin', mic: 0.5, result: 'S' }], patientAge: 41, patientGender: 'Male', collectedAt: daysAgo(62), submittedBy: tid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'ICU' }, antibiotics: [{ name: 'Oxacillin', mic: 32, result: 'R' }, { name: 'Vancomycin', mic: 1, result: 'S' }, { name: 'Clindamycin', mic: 8, result: 'R' }, { name: 'Erythromycin', mic: 16, result: 'R' }, { name: 'Linezolid', mic: 2, result: 'S' }], patientAge: 68, patientGender: 'Male', collectedAt: daysAgo(67), submittedBy: tid, notes: 'MRSA pneumonia.' },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Burns Unit' }, antibiotics: [{ name: 'Oxacillin', mic: 8, result: 'R' }, { name: 'Vancomycin', mic: 2, result: 'S' }, { name: 'Rifampicin', mic: 0.5, result: 'S' }, { name: 'Daptomycin', mic: 1, result: 'S' }], patientAge: 23, patientGender: 'Female', collectedAt: daysAgo(72), submittedBy: tid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'environmental', location: { site: 'Dialysis Unit Surface', city: 'Delhi' }, antibiotics: [{ name: 'Oxacillin', mic: 16, result: 'R' }, { name: 'Erythromycin', mic: 8, result: 'R' }, { name: 'Vancomycin', mic: 1, result: 'S' }, { name: 'Tetracycline', mic: 4, result: 'I' }], collectedAt: daysAgo(77), submittedBy: rid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Nephrology' }, antibiotics: [{ name: 'Oxacillin', mic: 0.5, result: 'S' }, { name: 'Clindamycin', mic: 0.25, result: 'S' }, { name: 'Erythromycin', mic: 2, result: 'I' }, { name: 'Ciprofloxacin', mic: 1, result: 'S' }], patientAge: 55, patientGender: 'Female', collectedAt: daysAgo(82), submittedBy: tid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'General Ward' }, antibiotics: [{ name: 'Oxacillin', mic: 4, result: 'R' }, { name: 'Erythromycin', mic: 4, result: 'R' }, { name: 'Tetracycline', mic: 8, result: 'R' }, { name: 'Ciprofloxacin', mic: 4, result: 'R' }, { name: 'Vancomycin', mic: 1, result: 'S' }], patientAge: 37, patientGender: 'Male', collectedAt: daysAgo(87), submittedBy: tid },
    { pathogen: 'S. aureus', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Cardiology' }, antibiotics: [{ name: 'Oxacillin', mic: 1, result: 'S' }, { name: 'Erythromycin', mic: 1, result: 'S' }, { name: 'Clindamycin', mic: 0.5, result: 'S' }, { name: 'Tetracycline', mic: 2, result: 'S' }], patientAge: 61, patientGender: 'Female', collectedAt: daysAgo(92), submittedBy: tid },

    // ── K. pneumoniae (20 samples) ───────────────────────────────────
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'NICU' }, antibiotics: [{ name: 'Meropenem', mic: 16, result: 'R' }, { name: 'Imipenem', mic: 8, result: 'R' }, { name: 'Ceftazidime', mic: 64, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 2, result: 'I' }], patientAge: 0, patientGender: 'Male', collectedAt: daysAgo(4), submittedBy: tid, notes: 'CRKP. Outbreak investigation initiated.' },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'ICU' }, antibiotics: [{ name: 'Meropenem', mic: 4, result: 'I' }, { name: 'Ceftazidime', mic: 32, result: 'R' }, { name: 'Amikacin', mic: 8, result: 'S' }, { name: 'Ciprofloxacin', mic: 8, result: 'R' }], patientAge: 61, patientGender: 'Male', collectedAt: daysAgo(9), submittedBy: tid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Medicine Ward' }, antibiotics: [{ name: 'Meropenem', mic: 0.5, result: 'S' }, { name: 'Ceftriaxone', mic: 1, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }, { name: 'Ciprofloxacin', mic: 0.5, result: 'S' }], patientAge: 38, patientGender: 'Female', collectedAt: daysAgo(15), submittedBy: tid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Hospital Drain', city: 'Delhi' }, antibiotics: [{ name: 'Meropenem', mic: 8, result: 'R' }, { name: 'Ceftazidime', mic: 128, result: 'R' }, { name: 'Colistin', mic: 2, result: 'S' }, { name: 'Amikacin', mic: 32, result: 'R' }], collectedAt: daysAgo(11), submittedBy: rid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Pulmonology' }, antibiotics: [{ name: 'Meropenem', mic: 2, result: 'S' }, { name: 'Ceftriaxone', mic: 4, result: 'I' }, { name: 'Ciprofloxacin', mic: 2, result: 'S' }, { name: 'Amikacin', mic: 8, result: 'S' }], patientAge: 56, patientGender: 'Male', collectedAt: daysAgo(19), submittedBy: tid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Oncology' }, antibiotics: [{ name: 'Meropenem', mic: 16, result: 'R' }, { name: 'Ceftazidime', mic: 64, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 2, result: 'I' }, { name: 'Fosfomycin', mic: 64, result: 'R' }], patientAge: 49, patientGender: 'Female', collectedAt: daysAgo(23), submittedBy: tid, notes: 'Neutropenic fever in chemo patient.' },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Urology' }, antibiotics: [{ name: 'Meropenem', mic: 1, result: 'S' }, { name: 'Ciprofloxacin', mic: 1, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }, { name: 'Ceftriaxone', mic: 2, result: 'S' }], patientAge: 70, patientGender: 'Male', collectedAt: daysAgo(29), submittedBy: tid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'ICU Ventilator Circuit', city: 'Delhi' }, antibiotics: [{ name: 'Meropenem', mic: 32, result: 'R' }, { name: 'Imipenem', mic: 16, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Ceftazidime', mic: 128, result: 'R' }], collectedAt: daysAgo(34), submittedBy: rid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Surgery Ward' }, antibiotics: [{ name: 'Meropenem', mic: 4, result: 'I' }, { name: 'Ceftriaxone', mic: 16, result: 'R' }, { name: 'Amikacin', mic: 16, result: 'I' }, { name: 'Ciprofloxacin', mic: 8, result: 'R' }], patientAge: 44, patientGender: 'Male', collectedAt: daysAgo(39), submittedBy: tid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Neonatology' }, antibiotics: [{ name: 'Meropenem', mic: 8, result: 'R' }, { name: 'Amikacin', mic: 4, result: 'S' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 1, result: 'S' }], patientAge: 0, patientGender: 'Female', collectedAt: daysAgo(44), submittedBy: tid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Transplant ICU' }, antibiotics: [{ name: 'Meropenem', mic: 32, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 2, result: 'I' }, { name: 'Fosfomycin', mic: 32, result: 'R' }], patientAge: 36, patientGender: 'Male', collectedAt: daysAgo(49), submittedBy: tid, notes: 'Post-renal transplant infection.' },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Wastewater Treatment Plant', city: 'Dehradun' }, antibiotics: [{ name: 'Meropenem', mic: 4, result: 'I' }, { name: 'Ceftazidime', mic: 16, result: 'R' }, { name: 'Amikacin', mic: 8, result: 'S' }], collectedAt: daysAgo(54), submittedBy: rid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Paediatrics' }, antibiotics: [{ name: 'Meropenem', mic: 0.5, result: 'S' }, { name: 'Ceftriaxone', mic: 1, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }, { name: 'Ciprofloxacin', mic: 1, result: 'S' }], patientAge: 9, patientGender: 'Male', collectedAt: daysAgo(59), submittedBy: tid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Neurology' }, antibiotics: [{ name: 'Meropenem', mic: 8, result: 'R' }, { name: 'Imipenem', mic: 8, result: 'R' }, { name: 'Ceftazidime', mic: 32, result: 'R' }, { name: 'Colistin', mic: 2, result: 'S' }], patientAge: 67, patientGender: 'Female', collectedAt: daysAgo(64), submittedBy: tid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Medicine Ward' }, antibiotics: [{ name: 'Meropenem', mic: 1, result: 'S' }, { name: 'Ceftriaxone', mic: 2, result: 'S' }, { name: 'Ciprofloxacin', mic: 1, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }], patientAge: 33, patientGender: 'Male', collectedAt: daysAgo(69), submittedBy: tid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'River Water Sample', city: 'Haridwar' }, antibiotics: [{ name: 'Meropenem', mic: 16, result: 'R' }, { name: 'Ceftazidime', mic: 64, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Amikacin', mic: 16, result: 'R' }], collectedAt: daysAgo(74), submittedBy: rid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Cardiothoracic' }, antibiotics: [{ name: 'Meropenem', mic: 4, result: 'I' }, { name: 'Ceftriaxone', mic: 8, result: 'R' }, { name: 'Amikacin', mic: 8, result: 'S' }, { name: 'Colistin', mic: 1, result: 'S' }], patientAge: 58, patientGender: 'Male', collectedAt: daysAgo(79), submittedBy: tid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Burns Unit' }, antibiotics: [{ name: 'Meropenem', mic: 32, result: 'R' }, { name: 'Ceftazidime', mic: 128, result: 'R' }, { name: 'Amikacin', mic: 32, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 2, result: 'I' }], patientAge: 27, patientGender: 'Female', collectedAt: daysAgo(84), submittedBy: tid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Geriatrics' }, antibiotics: [{ name: 'Meropenem', mic: 2, result: 'S' }, { name: 'Ceftriaxone', mic: 4, result: 'I' }, { name: 'Ciprofloxacin', mic: 4, result: 'I' }, { name: 'Amikacin', mic: 8, result: 'S' }], patientAge: 79, patientGender: 'Male', collectedAt: daysAgo(89), submittedBy: tid },
    { pathogen: 'K. pneumoniae', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Emergency' }, antibiotics: [{ name: 'Meropenem', mic: 1, result: 'S' }, { name: 'Ceftriaxone', mic: 1, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }, { name: 'Ciprofloxacin', mic: 0.5, result: 'S' }], patientAge: 42, patientGender: 'Female', collectedAt: daysAgo(94), submittedBy: tid },

    // ── A. baumannii (20 samples) ────────────────────────────────────
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'ICU' }, antibiotics: [{ name: 'Meropenem', mic: 32, result: 'R' }, { name: 'Imipenem', mic: 16, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 4, result: 'I' }, { name: 'Ampicillin-Sulbactam', mic: 32, result: 'R' }], patientAge: 58, patientGender: 'Male', collectedAt: daysAgo(3), submittedBy: tid, notes: 'CRAB. ICU cluster under investigation.' },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Trauma ICU' }, antibiotics: [{ name: 'Meropenem', mic: 64, result: 'R' }, { name: 'Colistin', mic: 2, result: 'S' }, { name: 'Rifampicin', mic: 4, result: 'I' }, { name: 'Tigecycline', mic: 2, result: 'I' }], patientAge: 25, patientGender: 'Male', collectedAt: daysAgo(7), submittedBy: tid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'ICU Surface Swab', city: 'Delhi' }, antibiotics: [{ name: 'Meropenem', mic: 16, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Chloramphenicol', mic: 16, result: 'R' }], collectedAt: daysAgo(18), submittedBy: rid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Burns ICU' }, antibiotics: [{ name: 'Meropenem', mic: 128, result: 'R' }, { name: 'Imipenem', mic: 64, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 4, result: 'I' }], patientAge: 31, patientGender: 'Female', collectedAt: daysAgo(21), submittedBy: tid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Neurosurgery ICU' }, antibiotics: [{ name: 'Meropenem', mic: 16, result: 'R' }, { name: 'Ampicillin-Sulbactam', mic: 16, result: 'I' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Rifampicin', mic: 2, result: 'S' }], patientAge: 46, patientGender: 'Male', collectedAt: daysAgo(26), submittedBy: tid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Ventilator Surface', city: 'Delhi' }, antibiotics: [{ name: 'Meropenem', mic: 32, result: 'R' }, { name: 'Imipenem', mic: 16, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }], collectedAt: daysAgo(31), submittedBy: rid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Thoracic Surgery' }, antibiotics: [{ name: 'Meropenem', mic: 8, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 2, result: 'S' }, { name: 'Rifampicin', mic: 1, result: 'S' }], patientAge: 55, patientGender: 'Female', collectedAt: daysAgo(36), submittedBy: tid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'MICU' }, antibiotics: [{ name: 'Meropenem', mic: 64, result: 'R' }, { name: 'Imipenem', mic: 32, result: 'R' }, { name: 'Colistin', mic: 2, result: 'S' }, { name: 'Ampicillin-Sulbactam', mic: 64, result: 'R' }, { name: 'Tigecycline', mic: 4, result: 'I' }], patientAge: 73, patientGender: 'Male', collectedAt: daysAgo(41), submittedBy: tid, notes: 'XDR A. baumannii. Only colistin active.' },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Hospital Floor Swab', city: 'Delhi' }, antibiotics: [{ name: 'Meropenem', mic: 16, result: 'R' }, { name: 'Chloramphenicol', mic: 8, result: 'I' }, { name: 'Colistin', mic: 1, result: 'S' }], collectedAt: daysAgo(46), submittedBy: rid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Respiratory ICU' }, antibiotics: [{ name: 'Meropenem', mic: 32, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 2, result: 'I' }], patientAge: 62, patientGender: 'Female', collectedAt: daysAgo(51), submittedBy: tid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Trauma Ward' }, antibiotics: [{ name: 'Meropenem', mic: 4, result: 'I' }, { name: 'Ampicillin-Sulbactam', mic: 8, result: 'S' }, { name: 'Ciprofloxacin', mic: 4, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }], patientAge: 19, patientGender: 'Male', collectedAt: daysAgo(56), submittedBy: tid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Ambulance Surface', city: 'Delhi' }, antibiotics: [{ name: 'Meropenem', mic: 8, result: 'R' }, { name: 'Imipenem', mic: 8, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }], collectedAt: daysAgo(61), submittedBy: rid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Cardiac ICU' }, antibiotics: [{ name: 'Meropenem', mic: 64, result: 'R' }, { name: 'Colistin', mic: 2, result: 'S' }, { name: 'Rifampicin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 2, result: 'I' }], patientAge: 68, patientGender: 'Male', collectedAt: daysAgo(66), submittedBy: tid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Paediatric ICU' }, antibiotics: [{ name: 'Meropenem', mic: 16, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 4, result: 'I' }], patientAge: 3, patientGender: 'Female', collectedAt: daysAgo(71), submittedBy: tid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'CT Scanner Surface', city: 'Delhi' }, antibiotics: [{ name: 'Meropenem', mic: 32, result: 'R' }, { name: 'Chloramphenicol', mic: 16, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }], collectedAt: daysAgo(76), submittedBy: rid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Oncology' }, antibiotics: [{ name: 'Meropenem', mic: 8, result: 'R' }, { name: 'Imipenem', mic: 4, result: 'I' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 2, result: 'S' }], patientAge: 51, patientGender: 'Male', collectedAt: daysAgo(81), submittedBy: tid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'ICU' }, antibiotics: [{ name: 'Meropenem', mic: 64, result: 'R' }, { name: 'Imipenem', mic: 32, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Ampicillin-Sulbactam', mic: 128, result: 'R' }], patientAge: 44, patientGender: 'Female', collectedAt: daysAgo(86), submittedBy: tid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Laundry Water Sample', city: 'Delhi' }, antibiotics: [{ name: 'Meropenem', mic: 16, result: 'R' }, { name: 'Colistin', mic: 2, result: 'S' }, { name: 'Chloramphenicol', mic: 8, result: 'I' }], collectedAt: daysAgo(91), submittedBy: rid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Emergency ICU' }, antibiotics: [{ name: 'Meropenem', mic: 32, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 2, result: 'I' }, { name: 'Rifampicin', mic: 0.5, result: 'S' }], patientAge: 38, patientGender: 'Male', collectedAt: daysAgo(96), submittedBy: tid },
    { pathogen: 'A. baumannii', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'General Surgery' }, antibiotics: [{ name: 'Meropenem', mic: 4, result: 'I' }, { name: 'Ampicillin-Sulbactam', mic: 4, result: 'S' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 1, result: 'S' }], patientAge: 29, patientGender: 'Female', collectedAt: daysAgo(100), submittedBy: tid },

    // ── P. aeruginosa (10 samples) ───────────────────────────────────
    { pathogen: 'P. aeruginosa', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Pulmonology' }, antibiotics: [{ name: 'Piperacillin-Tazobactam', mic: 64, result: 'R' }, { name: 'Ceftazidime', mic: 16, result: 'R' }, { name: 'Meropenem', mic: 4, result: 'I' }, { name: 'Amikacin', mic: 8, result: 'S' }, { name: 'Colistin', mic: 1, result: 'S' }], patientAge: 43, patientGender: 'Female', collectedAt: daysAgo(5), submittedBy: tid, notes: 'Chronic lung infection in CF patient.' },
    { pathogen: 'P. aeruginosa', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Burns Unit' }, antibiotics: [{ name: 'Piperacillin-Tazobactam', mic: 16, result: 'I' }, { name: 'Ciprofloxacin', mic: 2, result: 'S' }, { name: 'Meropenem', mic: 1, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }], patientAge: 35, patientGender: 'Male', collectedAt: daysAgo(13), submittedBy: tid },
    { pathogen: 'P. aeruginosa', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Swimming Pool Water', city: 'Dehradun' }, antibiotics: [{ name: 'Ciprofloxacin', mic: 4, result: 'R' }, { name: 'Ceftazidime', mic: 8, result: 'R' }, { name: 'Meropenem', mic: 2, result: 'I' }, { name: 'Amikacin', mic: 16, result: 'R' }], collectedAt: daysAgo(22), submittedBy: rid },
    { pathogen: 'P. aeruginosa', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'ICU' }, antibiotics: [{ name: 'Piperacillin-Tazobactam', mic: 128, result: 'R' }, { name: 'Ciprofloxacin', mic: 8, result: 'R' }, { name: 'Meropenem', mic: 16, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }], patientAge: 57, patientGender: 'Male', collectedAt: daysAgo(27), submittedBy: tid },
    { pathogen: 'P. aeruginosa', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Orthopaedics' }, antibiotics: [{ name: 'Piperacillin-Tazobactam', mic: 8, result: 'S' }, { name: 'Ciprofloxacin', mic: 1, result: 'S' }, { name: 'Meropenem', mic: 0.5, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }], patientAge: 42, patientGender: 'Female', collectedAt: daysAgo(37), submittedBy: tid },
    { pathogen: 'P. aeruginosa', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Tap Water Hospital', city: 'Delhi' }, antibiotics: [{ name: 'Ciprofloxacin', mic: 2, result: 'S' }, { name: 'Ceftazidime', mic: 4, result: 'S' }, { name: 'Meropenem', mic: 1, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }], collectedAt: daysAgo(48), submittedBy: rid },
    { pathogen: 'P. aeruginosa', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Burns ICU' }, antibiotics: [{ name: 'Piperacillin-Tazobactam', mic: 64, result: 'R' }, { name: 'Ceftazidime', mic: 32, result: 'R' }, { name: 'Meropenem', mic: 8, result: 'R' }, { name: 'Colistin', mic: 1, result: 'S' }, { name: 'Amikacin', mic: 32, result: 'R' }], patientAge: 33, patientGender: 'Male', collectedAt: daysAgo(58), submittedBy: tid },
    { pathogen: 'P. aeruginosa', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Pulmonology' }, antibiotics: [{ name: 'Piperacillin-Tazobactam', mic: 32, result: 'R' }, { name: 'Ciprofloxacin', mic: 4, result: 'I' }, { name: 'Meropenem', mic: 4, result: 'I' }, { name: 'Amikacin', mic: 8, result: 'S' }], patientAge: 66, patientGender: 'Female', collectedAt: daysAgo(68), submittedBy: tid },
    { pathogen: 'P. aeruginosa', gramStain: 'Negative', sampleType: 'environmental', location: { site: 'Wound Irrigation Water', city: 'Delhi' }, antibiotics: [{ name: 'Ciprofloxacin', mic: 8, result: 'R' }, { name: 'Ceftazidime', mic: 16, result: 'R' }, { name: 'Meropenem', mic: 4, result: 'I' }], collectedAt: daysAgo(78), submittedBy: rid },
    { pathogen: 'P. aeruginosa', gramStain: 'Negative', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Dermatology' }, antibiotics: [{ name: 'Piperacillin-Tazobactam', mic: 8, result: 'S' }, { name: 'Ciprofloxacin', mic: 0.5, result: 'S' }, { name: 'Meropenem', mic: 0.5, result: 'S' }, { name: 'Amikacin', mic: 4, result: 'S' }], patientAge: 26, patientGender: 'Male', collectedAt: daysAgo(88), submittedBy: tid },

    // ── E. faecium (10 samples) ──────────────────────────────────────
    { pathogen: 'E. faecium', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Haematology' }, antibiotics: [{ name: 'Vancomycin', mic: 32, result: 'R' }, { name: 'Ampicillin', mic: 64, result: 'R' }, { name: 'Linezolid', mic: 2, result: 'S' }, { name: 'Daptomycin', mic: 1, result: 'S' }, { name: 'Tigecycline', mic: 0.12, result: 'S' }], patientAge: 51, patientGender: 'Female', collectedAt: daysAgo(2), submittedBy: tid, notes: 'VRE. Post-transplant.' },
    { pathogen: 'E. faecium', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Medicine Ward' }, antibiotics: [{ name: 'Vancomycin', mic: 4, result: 'I' }, { name: 'Ampicillin', mic: 16, result: 'R' }, { name: 'Linezolid', mic: 2, result: 'S' }, { name: 'Tetracycline', mic: 8, result: 'R' }], patientAge: 64, patientGender: 'Male', collectedAt: daysAgo(17), submittedBy: tid },
    { pathogen: 'E. faecium', gramStain: 'Positive', sampleType: 'environmental', location: { site: 'Poultry Farm Water', city: 'Haridwar' }, antibiotics: [{ name: 'Vancomycin', mic: 64, result: 'R' }, { name: 'Ampicillin', mic: 128, result: 'R' }, { name: 'Erythromycin', mic: 32, result: 'R' }, { name: 'Chloramphenicol', mic: 8, result: 'I' }], collectedAt: daysAgo(25), submittedBy: rid, notes: 'One Health surveillance.' },
    { pathogen: 'E. faecium', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'ICU' }, antibiotics: [{ name: 'Vancomycin', mic: 16, result: 'R' }, { name: 'Ampicillin', mic: 32, result: 'R' }, { name: 'Linezolid', mic: 2, result: 'S' }, { name: 'Daptomycin', mic: 1, result: 'S' }], patientAge: 58, patientGender: 'Male', collectedAt: daysAgo(32), submittedBy: tid },
    { pathogen: 'E. faecium', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'GTB Hospital', ward: 'Oncology' }, antibiotics: [{ name: 'Vancomycin', mic: 1, result: 'S' }, { name: 'Ampicillin', mic: 4, result: 'S' }, { name: 'Linezolid', mic: 2, result: 'S' }, { name: 'Tetracycline', mic: 4, result: 'I' }], patientAge: 47, patientGender: 'Female', collectedAt: daysAgo(43), submittedBy: tid },
    { pathogen: 'E. faecium', gramStain: 'Positive', sampleType: 'environmental', location: { site: 'Cattle Farm Soil', city: 'Dehradun' }, antibiotics: [{ name: 'Vancomycin', mic: 32, result: 'R' }, { name: 'Erythromycin', mic: 16, result: 'R' }, { name: 'Tetracycline', mic: 32, result: 'R' }, { name: 'Chloramphenicol', mic: 4, result: 'S' }], collectedAt: daysAgo(53), submittedBy: rid },
    { pathogen: 'E. faecium', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'AIIMS Delhi', ward: 'Nephrology' }, antibiotics: [{ name: 'Vancomycin', mic: 2, result: 'S' }, { name: 'Ampicillin', mic: 4, result: 'S' }, { name: 'Linezolid', mic: 2, result: 'S' }, { name: 'Daptomycin', mic: 0.5, result: 'S' }], patientAge: 54, patientGender: 'Male', collectedAt: daysAgo(63), submittedBy: tid },
    { pathogen: 'E. faecium', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'Safdarjung Hospital', ward: 'Surgery Ward' }, antibiotics: [{ name: 'Vancomycin', mic: 32, result: 'R' }, { name: 'Ampicillin', mic: 64, result: 'R' }, { name: 'Linezolid', mic: 4, result: 'I' }, { name: 'Daptomycin', mic: 2, result: 'S' }], patientAge: 39, patientGender: 'Female', collectedAt: daysAgo(73), submittedBy: tid },
    { pathogen: 'E. faecium', gramStain: 'Positive', sampleType: 'environmental', location: { site: 'Sewage Overflow', city: 'Delhi' }, antibiotics: [{ name: 'Vancomycin', mic: 64, result: 'R' }, { name: 'Ampicillin', mic: 128, result: 'R' }, { name: 'Erythromycin', mic: 32, result: 'R' }], collectedAt: daysAgo(83), submittedBy: rid },
    { pathogen: 'E. faecium', gramStain: 'Positive', sampleType: 'clinical', location: { hospital: 'Ram Manohar Lohia Hospital', ward: 'Cardiology' }, antibiotics: [{ name: 'Vancomycin', mic: 1, result: 'S' }, { name: 'Ampicillin', mic: 2, result: 'S' }, { name: 'Linezolid', mic: 2, result: 'S' }, { name: 'Tetracycline', mic: 2, result: 'S' }], patientAge: 72, patientGender: 'Male', collectedAt: daysAgo(93), submittedBy: tid },
  ];

  await Sample.insertMany(samples);
  console.log(`✅ Seeded ${samples.length} samples across 5 pathogens!`);
  console.log('👤 Researcher: researcher@demo.com / password123');
  console.log('👤 Technician: technician@demo.com / password123');
  process.exit(0);
};

seed().catch(err => { console.error('Seed failed:', err); process.exit(1); });
